version: "3.8"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - docker-network
    ports:
      - 80:80
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      docker-network:
        aliases:
          - backend
networks:
    docker-network: